### ISSUE TITLE
Business day option is ignored

### ISSUE THREAD

**Issue by kumo** [jgclark/NotePlan-review#15]
I saw that in the readme there is the option for business days and in calc_offset_date there is support for business days too,  but the `RE_REVIEW_INTERVALS` doesn't match 'b' or 'B'. It seems to work if I replace the regular expression with `RE_REVIEW_INTERVALS = '[0-9]+[bBdDwWmMqQ]'`, but I haven't done much testing yet.

**Comment by jgclark** [comment]
Hi.  Well spotted, and diagnosed.  Yes, the logic is in `calc_offset_date()`, but it's not triggered because of the missing `bB` in RE_REVIEW_INTERVALS.  Will fix imminently.

BTW, I've now re-implemented almost all of this code in the [Review plugin](https://github.com/NotePlan/plugins/tree/main/jgclark.Review) using the framework available from NotePlan 3.0.26 that I helped design with its developer Eduard.  Have you tried using that?

**Comment by kumo** [comment]
I'm not sure why, but I couldn't get the Review plugin to work, so I tried this script instead, and it worked instead.

**Comment by jgclark** [comment]
If you do get the chance to look at the plugin version again, please do let
me know how far you get before you hit errors. And then see what the Plugin
Console log shows (Help > Plugin Console on macOS).
